spring.application.name=bank-application

spring.datasource.url=jdbc:postgresql://localhost:5432/bank_v2
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update